# MySQL. Versions 5.5.8 and up are supported.
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 4
  username: root
  password: toor
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mokb_development

test:
  <<: *default
  database: mokb_test
  username: root
  password: toor
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: mokb_production
  username: mokb
  password: <%= ENV['MOKB_DATABASE_PASSWORD'] %>
